name: Bookstore service build & deploy
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'front-end-app/**'
      - 'infra/**'
      - 'queries.graphql'
      - 'db-schema/**'
jobs:
  Bookstore-app-build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: "docker build -t bookstore:latest ."
      - run: "docker tag bookstore:latest 341871682637.dkr.ecr.eu-central-1.amazonaws.com/bookstore-application:latest"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - run: "docker push 341871682637.dkr.ecr.eu-central-1.amazonaws.com/bookstore-application:latest"
