name: Bookstore service build & deploy
on:
  push:
    branches:
      - master
jobs:
  Bookstore-app-build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: Check out repository code
          uses: actions/checkout@v3
      - run: "docker build -t bookstore:latest ."
      - run: "docker tag bookstore:latest 341871682637.dkr.ecr.eu-central-1.amazonaws.com/bookstore-application:latest"