name: Bookstore service build & deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  Bookstore-app-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
          uses: Cvetomird91/node-js-uni@master
      - run: "docker build -t bookstore:latest ."
      - run: "docker tag bookstore:latest 341871682637.dkr.ecr.eu-central-1.amazonaws.com/bookstore-application:latest"